/**
 * Loop 1 — structural crawl.
 *
 * For each table in the source DB: discover columns + FKs, profile each
 * column, write rows into the catalog (tables / columns / column_profiles /
 * docs), and write the structural markdown to disk.
 */
import { createHash } from "node:crypto";
import type { Pool } from "pg";
import { catalogPool } from "../catalog/db";
import { audit } from "../catalog/queries";
import { listTables, profileColumn, type SourceTable, type ColumnProfile } from "./source-pg";
import { renderStructuralDoc, countProvenance } from "./markdown";
import { log } from "../shared/log";

function computeSchemaHash(t: SourceTable): string {
  const sig = t.columns
    .slice()
    .sort((a, b) => a.ordinal - b.ordinal)
    .map((c) => `${c.column_name}|${c.data_type}|${c.is_nullable}|${c.is_primary}|${c.fk_target ?? ""}`)
    .join("\n");
  return createHash("md5").update(sig).digest("hex");
}

// On-disk catalog mirror removed: the canonical doc is foundation_ai.docs.markdown
// (and the wiki_pages row generated by the tables-wiki agent). Path column
// in `docs` is kept for backward compat but populated with a synthetic
// `wiki:` URI rather than a real file path.

export async function ensureSource(name: string, kind: string, connUrl: string): Promise<number> {
  const r = await catalogPool.query<{ id: string }>(
    `INSERT INTO sources (name, kind, conn_url)
     VALUES ($1, $2, $3)
     ON CONFLICT (name) DO UPDATE SET conn_url = EXCLUDED.conn_url
     RETURNING id`,
    [name, kind, connUrl]
  );
  return Number(r.rows[0]!.id);
}

/**
 * Run Loop 1 once. `mode='full'` always re-profiles; `mode='delta'` skips
 * tables whose schema_hash hasn't changed (used by the periodic scheduler).
 * Returns the ids of tables that were profiled or marked dirty so Loop 2
 * can target them precisely.
 */
export async function runLoop1(
  sourceId: number,
  sourcePoolInstance: Pool,
  schema = "public",
  mode: "full" | "delta" = "full",
): Promise<{ profiled: number[]; dirty: number[] }> {
  log.info("loop1.start", { sourceId, schema, mode });
  const startedAt = Date.now();

  const allTables = await listTables(sourcePoolInstance, schema);

  // Filter by the source's `included_tables` allowlist if one is set.
  // Empty/null = all tables in the schema.
  const allowRow = await catalogPool.query<{ included_tables: string[] | null }>(
    `SELECT included_tables FROM sources WHERE id = $1`,
    [sourceId],
  );
  const allow = allowRow.rows[0]?.included_tables ?? null;
  const tables =
    Array.isArray(allow) && allow.length > 0
      ? allTables.filter((t) =>
          allow.includes(`${t.schema_name}.${t.table_name}`),
        )
      : allTables;

  log.info("loop1.tables_discovered", {
    count: tables.length,
    total_in_source: allTables.length,
    allowlist_size: Array.isArray(allow) ? allow.length : null,
  });

  const profiledIds: number[] = [];
  const dirtyIds: number[] = [];

  // Upsert table rows first so the UI can show them as "pending → profiling".
  for (const t of tables) {
    await catalogPool.query(
      `INSERT INTO tables (source_id, schema_name, table_name, row_count, status)
       VALUES ($1, $2, $3, $4, 'pending')
       ON CONFLICT (source_id, schema_name, table_name)
       DO UPDATE SET row_count = EXCLUDED.row_count`,
      [sourceId, t.schema_name, t.table_name, t.row_count],
    );
  }

  for (const t of tables) {
    const tableId = await getTableId(sourceId, t.schema_name, t.table_name);
    const newHash = computeSchemaHash(t);
    const existing = await catalogPool.query<{ schema_hash: string | null; status: string }>(
      `SELECT schema_hash, status FROM tables WHERE id = $1`,
      [tableId],
    );
    const oldHash = existing.rows[0]?.schema_hash ?? null;

    if (mode === "delta") {
      // First-time backfill — table already in catalog from initial boot; just
      // record the hash so future ticks can compare against it. Don't re-run
      // profileOneTable (which would downgrade status from 'ready' → 'profiled').
      if (oldHash === null) {
        await catalogPool.query(
          `UPDATE tables SET schema_hash = $1 WHERE id = $2`,
          [newHash, tableId],
        );
        continue;
      }
      // Hash unchanged — no work this tick.
      if (oldHash === newHash) continue;

      // Hash changed — mark dirty + re-profile + caller will re-enrich.
      await catalogPool.query(`UPDATE tables SET dirty = TRUE WHERE id = $1`, [tableId]);
      dirtyIds.push(tableId);
      await audit("worker:loop1", "schema_changed", `${t.schema_name}.${t.table_name}`, {
        old_hash: oldHash.slice(0, 8),
        new_hash: newHash.slice(0, 8),
      });
    }

    await profileOneTable(sourceId, sourcePoolInstance, t, newHash);
    profiledIds.push(tableId);
  }

  log.info("loop1.done", { sourceId, ms: Date.now() - startedAt, profiled: profiledIds.length, dirty: dirtyIds.length });
  return { profiled: profiledIds, dirty: dirtyIds };
}

async function profileOneTable(
  sourceId: number,
  sourcePoolInstance: Pool,
  t: SourceTable,
  schemaHash: string,
) {
  const tableId = await getTableId(sourceId, t.schema_name, t.table_name);
  await setStatus(tableId, "profiling");

  // Remove any columns that no longer exist in source — keeps catalog tight.
  const live = new Set(t.columns.map((c) => c.column_name));
  const stale = await catalogPool.query<{ id: number; column_name: string }>(
    `SELECT id, column_name FROM columns WHERE table_id = $1`,
    [tableId],
  );
  for (const row of stale.rows) {
    if (!live.has(row.column_name)) {
      await catalogPool.query(`DELETE FROM columns WHERE id = $1`, [row.id]);
      await audit("worker:loop1", "column_dropped", `${t.schema_name}.${t.table_name}.${row.column_name}`);
    }
  }

  // Upsert columns
  for (const c of t.columns) {
    await catalogPool.query(
      `INSERT INTO columns (table_id, column_name, ordinal, data_type, is_nullable, is_primary, fk_target)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (table_id, column_name) DO UPDATE
         SET ordinal = EXCLUDED.ordinal,
             data_type = EXCLUDED.data_type,
             is_nullable = EXCLUDED.is_nullable,
             is_primary = EXCLUDED.is_primary,
             fk_target = EXCLUDED.fk_target`,
      [tableId, c.column_name, c.ordinal, c.data_type, c.is_nullable, c.is_primary, c.fk_target]
    );
  }

  // Profile each column
  const profileMap = new Map<string, ColumnProfile>();
  for (const c of t.columns) {
    try {
      const p = await profileColumn(
        sourcePoolInstance,
        t.schema_name,
        t.table_name,
        c.column_name,
        c.data_type,
        t.row_count
      );
      profileMap.set(c.column_name, p);
      const colId = await getColumnId(tableId, c.column_name);
      await catalogPool.query(
        `INSERT INTO column_profiles (column_id, null_rate, distinct_count, min_value, max_value, top_values, histogram, sample_values, profiled_at)
         VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8::jsonb, now())
         ON CONFLICT (column_id) DO UPDATE
           SET null_rate = EXCLUDED.null_rate,
               distinct_count = EXCLUDED.distinct_count,
               min_value = EXCLUDED.min_value,
               max_value = EXCLUDED.max_value,
               top_values = EXCLUDED.top_values,
               histogram = EXCLUDED.histogram,
               sample_values = EXCLUDED.sample_values,
               profiled_at = now()`,
        [
          colId,
          p.null_rate,
          p.distinct_count,
          p.min_value,
          p.max_value,
          JSON.stringify(p.top_values),
          p.histogram ? JSON.stringify(p.histogram) : null,
          JSON.stringify(p.sample_values),
        ]
      );
    } catch (e) {
      log.warn("loop1.profile_column_failed", { table: t.table_name, column: c.column_name, err: String(e) });
    }
  }

  // Render structural markdown and persist it in foundation_ai.docs.
  const md = renderStructuralDoc(t, profileMap);
  const sourceName = await getSourceName(sourceId);
  const path = `wiki://${sourceName}/${t.schema_name}/${t.table_name}`;

  await catalogPool.query(
    `INSERT INTO docs (table_id, path, markdown, provenance, updated_at)
     VALUES ($1, $2, $3, $4::jsonb, now())
     ON CONFLICT (table_id) DO UPDATE
       SET path = EXCLUDED.path,
           markdown = EXCLUDED.markdown,
           provenance = EXCLUDED.provenance,
           updated_at = now()`,
    [tableId, path, md, JSON.stringify(countProvenance(md))]
  );

  await catalogPool.query(
    `UPDATE tables SET last_profiled_at = now(), schema_hash = $2 WHERE id = $1`,
    [tableId, schemaHash],
  );
  await setStatus(tableId, "profiled");

  await audit("worker:loop1", "profile_table", `${t.schema_name}.${t.table_name}`, {
    columns: t.columns.length,
    row_count: t.row_count,
    schema_hash: schemaHash.slice(0, 8),
  });
}

async function getTableId(sourceId: number, schema: string, table: string): Promise<number> {
  const r = await catalogPool.query<{ id: string }>(
    `SELECT id FROM tables WHERE source_id = $1 AND schema_name = $2 AND table_name = $3`,
    [sourceId, schema, table]
  );
  return Number(r.rows[0]!.id);
}

async function getColumnId(tableId: number, columnName: string): Promise<number> {
  const r = await catalogPool.query<{ id: string }>(
    `SELECT id FROM columns WHERE table_id = $1 AND column_name = $2`,
    [tableId, columnName]
  );
  return Number(r.rows[0]!.id);
}

async function getSourceName(sourceId: number): Promise<string> {
  const r = await catalogPool.query<{ name: string }>(`SELECT name FROM sources WHERE id = $1`, [sourceId]);
  return r.rows[0]!.name;
}

async function setStatus(tableId: number, status: string) {
  await catalogPool.query(`UPDATE tables SET status = $1 WHERE id = $2`, [status, tableId]);
}

